### ISSUE TITLE
Can't click grid rows

### ISSUE THREAD

**Issue by jonom** [silverstripe-australia/silverstripe-gridfieldextensions#135]
On most gridfields you can click anywhere on a grid row to edit a record. That doesn't work when using editablecolumns, but the highlight effect and pointer cursor still appear on hover creating a confusing user experience.

I would prefer if we could restore the clickable behaviour but if that can't be done for some reason I think we should remove the hover effect and pointer cursor.

**Comment by micschk** [comment]
I personally didn't associate the highlight with the ability to click a row (it's just a visual position-clue to me), the problem concerns just the pointer cursor. The pointer cursor gets set as inline css on the tr onhover, probably by the core gridfield js instead of gridfieldextensions(?)

I fixed this by overriding the inline styling (on the td) on editableCOLUMNS-enabled gridfields instead of changing the js behaviour;
```css
.cms .ss-gridfield-editable tbody td { cursor: default; }
.cms .ss-gridfield-editable tbody td a { cursor: pointer; } /* for custom actions, eg blogcategory */
```
On a side node, editableROWS is a different module: https://github.com/milkyway-multimedia/ss-gridfield-utils/blob/master/docs/en/EditableRow.md
